<div class="page-header">
    <h1><?=$serie->name?></h1>
    <p><?=$serie->summary?></p>
</div>

<div>
<?foreach($seasons as $season):?>
    <a href="/season/<?=$season->id?>" class="jsVideo" data-title="<?=$season->name?>" data-content="<?=$season->summary?>" data-placement="auto" data-trigger="hover">
        <img src="/image/<?=$season->image->id?>" class="img-thumbnail" width="224" alt="<?=$season->name?>"/>
    </a>
<?endforeach;?>
</div>
<script>
    $('.jsVideo').popover();
</script>