<?php

namespace MediaMine\CoreBundle\Repository\Tunnel;

use MediaMine\CoreBundle\Repository\AbstractRepository;

/**
 * SeasonRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SeasonRepository extends AbstractRepository
{
}
