<?php

namespace MediaMine\CoreBundle\Repository\Video;


use MediaMine\CoreBundle\Repository\AbstractRepository;
/**
 * StatRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class StatRepository extends AbstractRepository
{
}
