media_mine_core:
  system:
    paths:
      ffmpeg: /usr/bin/avconv
      ffprobe: /usr/bin/avprobe
  modules:
    mediamine:
      module:
        key: mediamine
        namespace: MediaMine\Core
        name: MediaMine
        version: 0.1
        lock: true
        installed: true
        enabled: true
      tunnels:
        xml:
          key : xml
          service : mediamine.tunnel.xmltunnel
          enabled : true
      user_settings:
        background:
          type: [random]
          content: [random]
        playlist:
          last: [0]
        player:
          desktop_bitrate: 300
          desktop_format: hls
          mobile_bitrate: 150
          mobile_format: flv
          last_video: [0]
          last_time: [0]
      settings:
        tunnel:
          person : [xml-tunnel]
          video : [xml-tunnel]
          group : [xml-tunnel]
        paths:
          video : ['/app/media/video']
        video:
          default-bitrate: [150,300,500,1000]
      actions:
        check:
          service: mediamine.job.check
        createdb:
          service: mediamine.job.createdb
        install:
          service: mediamine.job.install
        clearcache:
          service: mediamine.job.clearcache
        killencoding:
          service: mediamine.job.killencoding
        filescan:
          service: mediamine.job.filescan
        searchxmlvideo:
          service: mediamine.job.searchxmlvideo
        searchxmlgroup:
          service: mediamine.job.searchxmlgroup
        mergegroup:
          service: mediamine.job.mergegroup
        mergevideo:
          service: mediamine.job.mergevideo
        mergeperson:
          service: mediamine.job.mergeperson
        deduplicatevideo:
          service: mediamine.job.deduplicatevideo
        deduplicateseason:
          service: mediamine.job.deduplicateseason
        deduplicategroup:
          service: mediamine.job.deduplicategroup
        deduplicategenre:
          service: mediamine.job.deduplicategenre
        scan:
          service: mediamine.job.scan
      filetypes:
          video: ['avi', 'mkv', 'mov', 'mpg', 'mpeg', '3gp', 'asf', 'mp2', 'vob', 'flv', 'divx', 'bin', 'mp4', 'h264', 'webm', 'wmv', 'xvid']
      videotypes: ['series', 'movie']
      grouptypes: ['series', 'movie']
      staffroles: ['actor', 'writer', 'director', 'guest']