################################# MEDIAMINE #################################
MediaMineCoreBundle:
    resource: "@MediaMineCoreBundle/Resources/config/routing.yml"
    prefix:   /
MediaMineCoreBundleApi:
    resource: "@MediaMineCoreBundle/Resources/config/routing_api.yml"
    prefix:   /api

################################# SONATA #################################
admin:
    resource: '@SonataAdminBundle/Resources/config/routing/sonata_admin.xml'
    prefix: /admin

_sonata_admin:
    resource: .
    type: sonata_admin
    prefix: /admin

sonata_user:
    resource: '@SonataUserBundle/Resources/config/routing/admin_security.xml'
    prefix: /admin

sonata_user_security:
    resource: "@SonataUserBundle/Resources/config/routing/sonata_security_1.xml"

sonata_user_resetting:
    resource: "@SonataUserBundle/Resources/config/routing/sonata_resetting_1.xml"
    prefix: /resetting

sonata_user_profile:
    resource: "@SonataUserBundle/Resources/config/routing/sonata_profile_1.xml"
    prefix: /profile

sonata_user_register:
    resource: "@SonataUserBundle/Resources/config/routing/sonata_registration_1.xml"
    prefix: /register

sonata_user_change_password:
    resource: "@SonataUserBundle/Resources/config/routing/sonata_change_password_1.xml"
    prefix: /profile

NelmioApiDocBundle:
    resource: "@NelmioApiDocBundle/Resources/config/routing.yml"
    prefix:   /api/doc

#fos_user:
#    resource: "@FOSUserBundle/Resources/config/routing/all.xml"

#REST
#rest :
#  type : rest
#  resource : "routing_rest.yml"
#  prefix : /api