<?php

namespace Application\Migrations;

use Doctrine\DBAL\Migrations\AbstractMigration;
use Doctrine\DBAL\Schema\Schema;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
class Version20141103222625 extends AbstractMigration
{
    public function up(Schema $schema)
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->abortIf($this->connection->getDatabasePlatform()->getName() != 'postgresql', 'Migration can only be executed safely on \'postgresql\'.');

        $this->addSql('CREATE SEQUENCE fos_user_user_id_seq INCREMENT BY 1 MINVALUE 1 START 1');
        $this->addSql('CREATE SEQUENCE fos_user_group_id_seq INCREMENT BY 1 MINVALUE 1 START 1');
        $this->addSql('CREATE TABLE system_job (id SERIAL NOT NULL, groupKey VARCHAR(255) NOT NULL, key VARCHAR(255) DEFAULT NULL, type VARCHAR(255) DEFAULT NULL, status VARCHAR(255) NOT NULL, service VARCHAR(255) NOT NULL, method VARCHAR(255) NOT NULL, params JSON DEFAULT NULL, nbTasks INT NOT NULL, nbTasksDone INT NOT NULL, createdAt TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, updatedAt TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, parentJob_id INT DEFAULT NULL, previousJob_id INT DEFAULT NULL, nextJob_id INT DEFAULT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE INDEX IDX_36604A234A4533A0 ON system_job (parentJob_id)');
        $this->addSql('CREATE INDEX IDX_36604A236D8C5E54 ON system_job (previousJob_id)');
        $this->addSql('CREATE INDEX IDX_36604A23E04C0C7F ON system_job (nextJob_id)');
        $this->addSql('CREATE TABLE system_module (id SERIAL NOT NULL, key VARCHAR(255) NOT NULL, namespace VARCHAR(255) NOT NULL, name VARCHAR(255) NOT NULL, lock BOOLEAN NOT NULL, version VARCHAR(255) NOT NULL, installed BOOLEAN NOT NULL, enabled BOOLEAN NOT NULL, admin JSON DEFAULT NULL, createdAt TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, updatedAt TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_1CAA93E98A90ABA9 ON system_module (key)');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_1CAA93E933E16B56 ON system_module (namespace)');
        $this->addSql('CREATE TABLE system_setting (id SERIAL NOT NULL, module_ref INT DEFAULT NULL, groupKey VARCHAR(255) NOT NULL, key VARCHAR(255) NOT NULL, value JSON NOT NULL, size INT NOT NULL, editable BOOLEAN NOT NULL, createdAt TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, updatedAt TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE INDEX IDX_7307C40BF81C3757 ON system_setting (module_ref)');
        $this->addSql('CREATE UNIQUE INDEX unique_group_key ON system_setting (groupKey, key)');
        $this->addSql('CREATE TABLE system_tunnel (id SERIAL NOT NULL, module_ref INT DEFAULT NULL, key VARCHAR(255) NOT NULL, service VARCHAR(255) NOT NULL, enabled BOOLEAN NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_C5F3E0818A90ABA9 ON system_tunnel (key)');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_C5F3E081E19D9AD2 ON system_tunnel (service)');
        $this->addSql('CREATE INDEX IDX_C5F3E081F81C3757 ON system_tunnel (module_ref)');
        $this->addSql('CREATE TABLE file_file (id SERIAL NOT NULL, directory_ref INT DEFAULT NULL, name VARCHAR(255) NOT NULL, pathKey TEXT NOT NULL, status VARCHAR(255) NOT NULL, extension VARCHAR(255) NOT NULL, size BIGINT NOT NULL, modificationDate TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, createdAt TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, updatedAt TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE INDEX IDX_5635E7E1F274CE3 ON file_file (directory_ref)');
        $this->addSql('CREATE INDEX file_file_extension_idx ON file_file (extension)');
        $this->addSql('CREATE TABLE file_directory (id SERIAL NOT NULL, parent_directory_ref INT DEFAULT NULL, name VARCHAR(255) NOT NULL, path TEXT NOT NULL, modificationDate TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, status VARCHAR(255) NOT NULL, createdAt TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, updatedAt TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE INDEX IDX_C877FBACC3A12F71 ON file_directory (parent_directory_ref)');
        $this->addSql('CREATE TABLE file_extension (name VARCHAR(255) NOT NULL, type VARCHAR(255) NOT NULL, PRIMARY KEY(name))');
        $this->addSql('CREATE TABLE common_country (id SERIAL NOT NULL, name TEXT NOT NULL, language TEXT NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE INDEX common_country_name_idx ON common_country (name)');
        $this->addSql('CREATE TABLE common_person (id SERIAL NOT NULL, country_ref INT DEFAULT NULL, slug VARCHAR(128) NOT NULL, name VARCHAR(255) NOT NULL, firstName VARCHAR(255) DEFAULT NULL, lastName VARCHAR(255) DEFAULT NULL, birthDate TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, deathDate TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, summary TEXT DEFAULT NULL, createdAt TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, updatedAt TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_4FEA42E3989D9B62 ON common_person (slug)');
        $this->addSql('CREATE INDEX IDX_4FEA42E32F470832 ON common_person (country_ref)');
        $this->addSql('CREATE INDEX common_person_name_idx ON common_person (name)');
        $this->addSql('CREATE TABLE common_person_image (person_ref INT NOT NULL, file_ref INT NOT NULL, PRIMARY KEY(person_ref, file_ref))');
        $this->addSql('CREATE INDEX IDX_3FE2E1679722F9B8 ON common_person_image (person_ref)');
        $this->addSql('CREATE INDEX IDX_3FE2E1673B2CB03A ON common_person_image (file_ref)');
        $this->addSql('CREATE TABLE video_video_file_meta (id SERIAL NOT NULL, file_ref INT DEFAULT NULL, width TEXT NOT NULL, height TEXT NOT NULL, createdAt TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, updatedAt TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_71EF50A43B2CB03A ON video_video_file_meta (file_ref)');
        $this->addSql('CREATE TABLE video_staff (id SERIAL NOT NULL, video_ref INT DEFAULT NULL, person_ref INT DEFAULT NULL, character_ref INT DEFAULT NULL, role VARCHAR(255) NOT NULL, createdAt TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, updatedAt TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE INDEX IDX_CD0CFA30EEF6FBA7 ON video_staff (video_ref)');
        $this->addSql('CREATE INDEX IDX_CD0CFA309722F9B8 ON video_staff (person_ref)');
        $this->addSql('CREATE INDEX IDX_CD0CFA305FC5E53D ON video_staff (character_ref)');
        $this->addSql('CREATE TABLE video_staff_image (staff_ref INT NOT NULL, file_ref INT NOT NULL, PRIMARY KEY(staff_ref, file_ref))');
        $this->addSql('CREATE INDEX IDX_9A5A1D399A63A56A ON video_staff_image (staff_ref)');
        $this->addSql('CREATE INDEX IDX_9A5A1D393B2CB03A ON video_staff_image (file_ref)');
        $this->addSql('CREATE TABLE video_review (id SERIAL NOT NULL, review TEXT NOT NULL, source TEXT NOT NULL, createdAt TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, updatedAt TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE TABLE video_video_file (id SERIAL NOT NULL, video_ref INT DEFAULT NULL, file_ref INT DEFAULT NULL, picture_ref INT DEFAULT NULL, quality_ref INT DEFAULT NULL, stat_ref INT DEFAULT NULL, createdAt TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, updatedAt TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE INDEX IDX_BAF737AEEF6FBA7 ON video_video_file (video_ref)');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_BAF737A3B2CB03A ON video_video_file (file_ref)');
        $this->addSql('CREATE INDEX IDX_BAF737A248BBD90 ON video_video_file (picture_ref)');
        $this->addSql('CREATE INDEX IDX_BAF737A8A086E0A ON video_video_file (quality_ref)');
        $this->addSql('CREATE INDEX IDX_BAF737AE860DF97 ON video_video_file (stat_ref)');
        $this->addSql('CREATE TABLE video_file_language (video_file_ref INT NOT NULL, country_ref INT NOT NULL, PRIMARY KEY(video_file_ref, country_ref))');
        $this->addSql('CREATE INDEX IDX_6EF1D21893AE8286 ON video_file_language (video_file_ref)');
        $this->addSql('CREATE INDEX IDX_6EF1D2182F470832 ON video_file_language (country_ref)');
        $this->addSql('CREATE TABLE video_stat (id SERIAL NOT NULL, nbView INT NOT NULL, lastView TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, createdAt TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, updatedAt TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE TABLE video_group_type (id SERIAL NOT NULL, name TEXT NOT NULL, summary TEXT DEFAULT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE TABLE video_picture (id SERIAL NOT NULL, name TEXT NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE TABLE video_staff_role (id SERIAL NOT NULL, name TEXT NOT NULL, summary TEXT DEFAULT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_35F8E4535E237E06 ON video_staff_role (name)');
        $this->addSql('CREATE TABLE video_character (id SERIAL NOT NULL, video_ref INT DEFAULT NULL, slug VARCHAR(128) NOT NULL, name VARCHAR(255) NOT NULL, summary TEXT DEFAULT NULL, createdAt TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, updatedAt TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_5105CDA1989D9B62 ON video_character (slug)');
        $this->addSql('CREATE INDEX IDX_5105CDA1EEF6FBA7 ON video_character (video_ref)');
        $this->addSql('CREATE INDEX video_character_name_idx ON video_character (name)');
        $this->addSql('CREATE TABLE video_rating (id SERIAL NOT NULL, localRate INT NOT NULL, localNbVote INT NOT NULL, webRate INT NOT NULL, webNbVote INT NOT NULL, createdAt TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, updatedAt TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE TABLE video_type (id SERIAL NOT NULL, slug VARCHAR(128) NOT NULL, name TEXT NOT NULL, summary TEXT DEFAULT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_8B490AF5989D9B62 ON video_type (slug)');
        $this->addSql('CREATE TABLE video_quality (id SERIAL NOT NULL, name TEXT NOT NULL, width INT NOT NULL, height INT NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE TABLE video_group (id SERIAL NOT NULL, directory_ref INT DEFAULT NULL, name VARCHAR(255) NOT NULL, slug VARCHAR(128) NOT NULL, originalName VARCHAR(255) DEFAULT NULL, summary TEXT DEFAULT NULL, type VARCHAR(255) DEFAULT NULL, createdAt TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, updatedAt TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_E2A24D67989D9B62 ON video_group (slug)');
        $this->addSql('CREATE INDEX IDX_E2A24D671F274CE3 ON video_group (directory_ref)');
        $this->addSql('CREATE INDEX video_group_name_idx ON video_group (name)');
        $this->addSql('CREATE TABLE video_group_image (group_ref INT NOT NULL, file_ref INT NOT NULL, PRIMARY KEY(group_ref, file_ref))');
        $this->addSql('CREATE INDEX IDX_B7939E9997FDD6DA ON video_group_image (group_ref)');
        $this->addSql('CREATE INDEX IDX_B7939E993B2CB03A ON video_group_image (file_ref)');
        $this->addSql('CREATE TABLE video_group_genre (group_ref INT NOT NULL, genre_ref INT NOT NULL, PRIMARY KEY(group_ref, genre_ref))');
        $this->addSql('CREATE INDEX IDX_F1FEA93E97FDD6DA ON video_group_genre (group_ref)');
        $this->addSql('CREATE INDEX IDX_F1FEA93EF2F1CD16 ON video_group_genre (genre_ref)');
        $this->addSql('CREATE TABLE video_video (id SERIAL NOT NULL, group_ref INT DEFAULT NULL, season_ref INT DEFAULT NULL, country_ref INT DEFAULT NULL, rating_ref INT DEFAULT NULL, review_ref INT DEFAULT NULL, slug VARCHAR(128) NOT NULL, name VARCHAR(255) NOT NULL, originalName VARCHAR(255) DEFAULT NULL, filePathKey TEXT DEFAULT NULL, summary TEXT DEFAULT NULL, year INT DEFAULT NULL, episode INT DEFAULT NULL, type VARCHAR(255) DEFAULT NULL, createdAt TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, updatedAt TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_F3A5D38E989D9B62 ON video_video (slug)');
        $this->addSql('CREATE INDEX IDX_F3A5D38E97FDD6DA ON video_video (group_ref)');
        $this->addSql('CREATE INDEX IDX_F3A5D38E8E217473 ON video_video (season_ref)');
        $this->addSql('CREATE INDEX IDX_F3A5D38E2F470832 ON video_video (country_ref)');
        $this->addSql('CREATE INDEX IDX_F3A5D38EDB6035A ON video_video (rating_ref)');
        $this->addSql('CREATE INDEX IDX_F3A5D38E1858326A ON video_video (review_ref)');
        $this->addSql('CREATE INDEX video_video_name_idx ON video_video (name)');
        $this->addSql('CREATE TABLE video_video_image (video_ref INT NOT NULL, file_ref INT NOT NULL, PRIMARY KEY(video_ref, file_ref))');
        $this->addSql('CREATE INDEX IDX_68DDBC5CEEF6FBA7 ON video_video_image (video_ref)');
        $this->addSql('CREATE INDEX IDX_68DDBC5C3B2CB03A ON video_video_image (file_ref)');
        $this->addSql('CREATE TABLE video_video_genre (video_ref INT NOT NULL, genre_ref INT NOT NULL, PRIMARY KEY(video_ref, genre_ref))');
        $this->addSql('CREATE INDEX IDX_2EB08BFBEEF6FBA7 ON video_video_genre (video_ref)');
        $this->addSql('CREATE INDEX IDX_2EB08BFBF2F1CD16 ON video_video_genre (genre_ref)');
        $this->addSql('CREATE TABLE video_genre (id SERIAL NOT NULL, slug VARCHAR(128) NOT NULL, name TEXT NOT NULL, summary TEXT DEFAULT NULL, createdAt TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, updatedAt TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_C323A5A989D9B62 ON video_genre (slug)');
        $this->addSql('CREATE TABLE video_season (id SERIAL NOT NULL, group_ref INT DEFAULT NULL, directory_ref INT DEFAULT NULL, slug VARCHAR(128) NOT NULL, number INT NOT NULL, name TEXT NOT NULL, summary TEXT DEFAULT NULL, createdAt TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, updatedAt TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_C8B3FB64989D9B62 ON video_season (slug)');
        $this->addSql('CREATE INDEX IDX_C8B3FB6497FDD6DA ON video_season (group_ref)');
        $this->addSql('CREATE INDEX IDX_C8B3FB641F274CE3 ON video_season (directory_ref)');
        $this->addSql('CREATE INDEX video_season_name_idx ON video_season (name)');
        $this->addSql('CREATE TABLE video_season_image (season_ref INT NOT NULL, file_ref INT NOT NULL, PRIMARY KEY(season_ref, file_ref))');
        $this->addSql('CREATE INDEX IDX_73FFE24F8E217473 ON video_season_image (season_ref)');
        $this->addSql('CREATE INDEX IDX_73FFE24F3B2CB03A ON video_season_image (file_ref)');
        $this->addSql('CREATE TABLE tunnel_person (id SERIAL NOT NULL, tunnel_ref INT DEFAULT NULL, person_ref INT DEFAULT NULL, name VARCHAR(255) NOT NULL, firstName VARCHAR(255) DEFAULT NULL, lastName VARCHAR(255) DEFAULT NULL, country VARCHAR(255) DEFAULT NULL, birthDate TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, deathDate TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, summary TEXT DEFAULT NULL, raw JSON DEFAULT NULL, dataLanguage VARCHAR(255) DEFAULT NULL, createdAt TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, updatedAt TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE INDEX IDX_C56FB71DC44FB2DF ON tunnel_person (tunnel_ref)');
        $this->addSql('CREATE INDEX IDX_C56FB71D9722F9B8 ON tunnel_person (person_ref)');
        $this->addSql('CREATE UNIQUE INDEX unique_tunnel_person_ref ON tunnel_person (tunnel_ref, person_ref)');
        $this->addSql('CREATE TABLE tunnel_person_image (person_ref INT NOT NULL, file_ref INT NOT NULL, PRIMARY KEY(person_ref, file_ref))');
        $this->addSql('CREATE INDEX IDX_A68B9E7C9722F9B8 ON tunnel_person_image (person_ref)');
        $this->addSql('CREATE INDEX IDX_A68B9E7C3B2CB03A ON tunnel_person_image (file_ref)');
        $this->addSql('CREATE TABLE tunnel_group (id SERIAL NOT NULL, group_ref INT DEFAULT NULL, tunnel_ref INT DEFAULT NULL, name TEXT NOT NULL, originalName TEXT NOT NULL, summary TEXT DEFAULT NULL, type VARCHAR(255) DEFAULT NULL, rating JSON DEFAULT NULL, staffs JSON DEFAULT NULL, genres JSON DEFAULT NULL, raw JSON DEFAULT NULL, dataLanguage VARCHAR(255) DEFAULT NULL, createdAt TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, updatedAt TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE INDEX IDX_A446D1497FDD6DA ON tunnel_group (group_ref)');
        $this->addSql('CREATE INDEX IDX_A446D14C44FB2DF ON tunnel_group (tunnel_ref)');
        $this->addSql('CREATE TABLE tunnel_group_image (group_ref INT NOT NULL, file_ref INT NOT NULL, PRIMARY KEY(group_ref, file_ref))');
        $this->addSql('CREATE INDEX IDX_AF01510E97FDD6DA ON tunnel_group_image (group_ref)');
        $this->addSql('CREATE INDEX IDX_AF01510E3B2CB03A ON tunnel_group_image (file_ref)');
        $this->addSql('CREATE TABLE tunnel_video (id SERIAL NOT NULL, tunnel_ref INT DEFAULT NULL, video_ref INT DEFAULT NULL, name VARCHAR(255) NOT NULL, originalName VARCHAR(255) DEFAULT NULL, summary TEXT DEFAULT NULL, year INT DEFAULT NULL, episode INT DEFAULT NULL, vgroup VARCHAR(255) DEFAULT NULL, season INT DEFAULT NULL, country VARCHAR(255) DEFAULT NULL, rating JSON DEFAULT NULL, review JSON DEFAULT NULL, type VARCHAR(255) DEFAULT NULL, genres JSON DEFAULT NULL, staffs JSON DEFAULT NULL, raw JSON DEFAULT NULL, dataLanguage VARCHAR(255) DEFAULT NULL, createdAt TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, updatedAt TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE INDEX IDX_1B43F3FDC44FB2DF ON tunnel_video (tunnel_ref)');
        $this->addSql('CREATE INDEX IDX_1B43F3FDEEF6FBA7 ON tunnel_video (video_ref)');
        $this->addSql('CREATE INDEX tunnel_video_name_idx ON tunnel_video (name)');
        $this->addSql('CREATE UNIQUE INDEX unique_tunnel_video_ref ON tunnel_video (tunnel_ref, video_ref)');
        $this->addSql('CREATE TABLE tunnel_video_image (video_ref INT NOT NULL, file_ref INT NOT NULL, PRIMARY KEY(video_ref, file_ref))');
        $this->addSql('CREATE INDEX IDX_704F73CBEEF6FBA7 ON tunnel_video_image (video_ref)');
        $this->addSql('CREATE INDEX IDX_704F73CB3B2CB03A ON tunnel_video_image (file_ref)');
        $this->addSql('CREATE TABLE tunnel_season (id SERIAL NOT NULL, season_ref INT DEFAULT NULL, tunnel_ref INT DEFAULT NULL, number INT NOT NULL, name TEXT NOT NULL, summary TEXT DEFAULT NULL, sgroup VARCHAR(255) DEFAULT NULL, raw JSON DEFAULT NULL, dataLanguage VARCHAR(255) DEFAULT NULL, createdAt TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, updatedAt TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE INDEX IDX_1573DC28E217473 ON tunnel_season (season_ref)');
        $this->addSql('CREATE INDEX IDX_1573DC2C44FB2DF ON tunnel_season (tunnel_ref)');
        $this->addSql('CREATE TABLE tunnel_season_image (season_ref INT NOT NULL, file_ref INT NOT NULL, PRIMARY KEY(season_ref, file_ref))');
        $this->addSql('CREATE INDEX IDX_1D8C76678E217473 ON tunnel_season_image (season_ref)');
        $this->addSql('CREATE INDEX IDX_1D8C76673B2CB03A ON tunnel_season_image (file_ref)');
        $this->addSql('CREATE TABLE fos_user_user (id INT NOT NULL, username VARCHAR(255) NOT NULL, username_canonical VARCHAR(255) NOT NULL, email VARCHAR(255) NOT NULL, email_canonical VARCHAR(255) NOT NULL, enabled BOOLEAN NOT NULL, salt VARCHAR(255) NOT NULL, password VARCHAR(255) NOT NULL, last_login TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, locked BOOLEAN NOT NULL, expired BOOLEAN NOT NULL, expires_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, confirmation_token VARCHAR(255) DEFAULT NULL, password_requested_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, roles TEXT NOT NULL, credentials_expired BOOLEAN NOT NULL, credentials_expire_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, date_of_birth TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, firstname VARCHAR(64) DEFAULT NULL, lastname VARCHAR(64) DEFAULT NULL, website VARCHAR(64) DEFAULT NULL, biography VARCHAR(1000) DEFAULT NULL, gender VARCHAR(1) DEFAULT NULL, locale VARCHAR(8) DEFAULT NULL, timezone VARCHAR(64) DEFAULT NULL, phone VARCHAR(64) DEFAULT NULL, facebook_uid VARCHAR(255) DEFAULT NULL, facebook_name VARCHAR(255) DEFAULT NULL, facebook_data TEXT DEFAULT NULL, twitter_uid VARCHAR(255) DEFAULT NULL, twitter_name VARCHAR(255) DEFAULT NULL, twitter_data TEXT DEFAULT NULL, gplus_uid VARCHAR(255) DEFAULT NULL, gplus_name VARCHAR(255) DEFAULT NULL, gplus_data TEXT DEFAULT NULL, token VARCHAR(255) DEFAULT NULL, two_step_code VARCHAR(255) DEFAULT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_C560D76192FC23A8 ON fos_user_user (username_canonical)');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_C560D761A0D96FBF ON fos_user_user (email_canonical)');
        $this->addSql('COMMENT ON COLUMN fos_user_user.roles IS \'(DC2Type:array)\'');
        $this->addSql('COMMENT ON COLUMN fos_user_user.facebook_data IS \'(DC2Type:json)\'');
        $this->addSql('COMMENT ON COLUMN fos_user_user.twitter_data IS \'(DC2Type:json)\'');
        $this->addSql('COMMENT ON COLUMN fos_user_user.gplus_data IS \'(DC2Type:json)\'');
        $this->addSql('CREATE TABLE fos_user_user_group (user_id INT NOT NULL, group_id INT NOT NULL, PRIMARY KEY(user_id, group_id))');
        $this->addSql('CREATE INDEX IDX_B3C77447A76ED395 ON fos_user_user_group (user_id)');
        $this->addSql('CREATE INDEX IDX_B3C77447FE54D947 ON fos_user_user_group (group_id)');
        $this->addSql('CREATE TABLE fos_user_group (id INT NOT NULL, name VARCHAR(255) NOT NULL, roles TEXT NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_583D1F3E5E237E06 ON fos_user_group (name)');
        $this->addSql('COMMENT ON COLUMN fos_user_group.roles IS \'(DC2Type:array)\'');
        $this->addSql('CREATE TABLE acl_classes (id SERIAL NOT NULL, class_type VARCHAR(200) NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_69DD750638A36066 ON acl_classes (class_type)');
        $this->addSql('CREATE TABLE acl_security_identities (id SERIAL NOT NULL, identifier VARCHAR(200) NOT NULL, username BOOLEAN NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_8835EE78772E836AF85E0677 ON acl_security_identities (identifier, username)');
        $this->addSql('CREATE TABLE acl_object_identities (id SERIAL NOT NULL, parent_object_identity_id INT DEFAULT NULL, class_id INT NOT NULL, object_identifier VARCHAR(100) NOT NULL, entries_inheriting BOOLEAN NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_9407E5494B12AD6EA000B10 ON acl_object_identities (object_identifier, class_id)');
        $this->addSql('CREATE INDEX IDX_9407E54977FA751A ON acl_object_identities (parent_object_identity_id)');
        $this->addSql('CREATE TABLE acl_object_identity_ancestors (object_identity_id INT NOT NULL, ancestor_id INT NOT NULL, PRIMARY KEY(object_identity_id, ancestor_id))');
        $this->addSql('CREATE INDEX IDX_825DE2993D9AB4A6 ON acl_object_identity_ancestors (object_identity_id)');
        $this->addSql('CREATE INDEX IDX_825DE299C671CEA1 ON acl_object_identity_ancestors (ancestor_id)');
        $this->addSql('CREATE TABLE acl_entries (id SERIAL NOT NULL, class_id INT NOT NULL, object_identity_id INT DEFAULT NULL, security_identity_id INT NOT NULL, field_name VARCHAR(50) DEFAULT NULL, ace_order SMALLINT NOT NULL, mask INT NOT NULL, granting BOOLEAN NOT NULL, granting_strategy VARCHAR(30) NOT NULL, audit_success BOOLEAN NOT NULL, audit_failure BOOLEAN NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_46C8B806EA000B103D9AB4A64DEF17BCE4289BF4 ON acl_entries (class_id, object_identity_id, field_name, ace_order)');
        $this->addSql('CREATE INDEX IDX_46C8B806EA000B103D9AB4A6DF9183C9 ON acl_entries (class_id, object_identity_id, security_identity_id)');
        $this->addSql('CREATE INDEX IDX_46C8B806EA000B10 ON acl_entries (class_id)');
        $this->addSql('CREATE INDEX IDX_46C8B8063D9AB4A6 ON acl_entries (object_identity_id)');
        $this->addSql('CREATE INDEX IDX_46C8B806DF9183C9 ON acl_entries (security_identity_id)');
        $this->addSql('ALTER TABLE system_job ADD CONSTRAINT FK_36604A234A4533A0 FOREIGN KEY (parentJob_id) REFERENCES system_job (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE system_job ADD CONSTRAINT FK_36604A236D8C5E54 FOREIGN KEY (previousJob_id) REFERENCES system_job (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE system_job ADD CONSTRAINT FK_36604A23E04C0C7F FOREIGN KEY (nextJob_id) REFERENCES system_job (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE system_setting ADD CONSTRAINT FK_7307C40BF81C3757 FOREIGN KEY (module_ref) REFERENCES system_module (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE system_tunnel ADD CONSTRAINT FK_C5F3E081F81C3757 FOREIGN KEY (module_ref) REFERENCES system_module (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE file_file ADD CONSTRAINT FK_5635E7E1F274CE3 FOREIGN KEY (directory_ref) REFERENCES file_directory (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE file_directory ADD CONSTRAINT FK_C877FBACC3A12F71 FOREIGN KEY (parent_directory_ref) REFERENCES file_directory (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE common_person ADD CONSTRAINT FK_4FEA42E32F470832 FOREIGN KEY (country_ref) REFERENCES common_country (id) ON DELETE SET NULL NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE common_person_image ADD CONSTRAINT FK_3FE2E1679722F9B8 FOREIGN KEY (person_ref) REFERENCES common_person (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE common_person_image ADD CONSTRAINT FK_3FE2E1673B2CB03A FOREIGN KEY (file_ref) REFERENCES file_file (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE video_video_file_meta ADD CONSTRAINT FK_71EF50A43B2CB03A FOREIGN KEY (file_ref) REFERENCES file_file (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE video_staff ADD CONSTRAINT FK_CD0CFA30EEF6FBA7 FOREIGN KEY (video_ref) REFERENCES video_video (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE video_staff ADD CONSTRAINT FK_CD0CFA309722F9B8 FOREIGN KEY (person_ref) REFERENCES common_person (id) ON DELETE SET NULL NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE video_staff ADD CONSTRAINT FK_CD0CFA305FC5E53D FOREIGN KEY (character_ref) REFERENCES video_character (id) ON DELETE SET NULL NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE video_staff_image ADD CONSTRAINT FK_9A5A1D399A63A56A FOREIGN KEY (staff_ref) REFERENCES video_staff (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE video_staff_image ADD CONSTRAINT FK_9A5A1D393B2CB03A FOREIGN KEY (file_ref) REFERENCES file_file (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE video_video_file ADD CONSTRAINT FK_BAF737AEEF6FBA7 FOREIGN KEY (video_ref) REFERENCES video_video (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE video_video_file ADD CONSTRAINT FK_BAF737A3B2CB03A FOREIGN KEY (file_ref) REFERENCES file_file (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE video_video_file ADD CONSTRAINT FK_BAF737A248BBD90 FOREIGN KEY (picture_ref) REFERENCES video_picture (id) ON DELETE SET NULL NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE video_video_file ADD CONSTRAINT FK_BAF737A8A086E0A FOREIGN KEY (quality_ref) REFERENCES video_quality (id) ON DELETE SET NULL NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE video_video_file ADD CONSTRAINT FK_BAF737AE860DF97 FOREIGN KEY (stat_ref) REFERENCES video_stat (id) ON DELETE SET NULL NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE video_file_language ADD CONSTRAINT FK_6EF1D21893AE8286 FOREIGN KEY (video_file_ref) REFERENCES video_video_file (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE video_file_language ADD CONSTRAINT FK_6EF1D2182F470832 FOREIGN KEY (country_ref) REFERENCES common_country (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE video_character ADD CONSTRAINT FK_5105CDA1EEF6FBA7 FOREIGN KEY (video_ref) REFERENCES video_video (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE video_group ADD CONSTRAINT FK_E2A24D671F274CE3 FOREIGN KEY (directory_ref) REFERENCES file_directory (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE video_group_image ADD CONSTRAINT FK_B7939E9997FDD6DA FOREIGN KEY (group_ref) REFERENCES video_group (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE video_group_image ADD CONSTRAINT FK_B7939E993B2CB03A FOREIGN KEY (file_ref) REFERENCES file_file (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE video_group_genre ADD CONSTRAINT FK_F1FEA93E97FDD6DA FOREIGN KEY (group_ref) REFERENCES video_group (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE video_group_genre ADD CONSTRAINT FK_F1FEA93EF2F1CD16 FOREIGN KEY (genre_ref) REFERENCES video_genre (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE video_video ADD CONSTRAINT FK_F3A5D38E97FDD6DA FOREIGN KEY (group_ref) REFERENCES video_group (id) ON DELETE SET NULL NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE video_video ADD CONSTRAINT FK_F3A5D38E8E217473 FOREIGN KEY (season_ref) REFERENCES video_season (id) ON DELETE SET NULL NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE video_video ADD CONSTRAINT FK_F3A5D38E2F470832 FOREIGN KEY (country_ref) REFERENCES common_country (id) ON DELETE SET NULL NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE video_video ADD CONSTRAINT FK_F3A5D38EDB6035A FOREIGN KEY (rating_ref) REFERENCES video_rating (id) ON DELETE SET NULL NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE video_video ADD CONSTRAINT FK_F3A5D38E1858326A FOREIGN KEY (review_ref) REFERENCES video_review (id) ON DELETE SET NULL NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE video_video_image ADD CONSTRAINT FK_68DDBC5CEEF6FBA7 FOREIGN KEY (video_ref) REFERENCES video_video (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE video_video_image ADD CONSTRAINT FK_68DDBC5C3B2CB03A FOREIGN KEY (file_ref) REFERENCES file_file (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE video_video_genre ADD CONSTRAINT FK_2EB08BFBEEF6FBA7 FOREIGN KEY (video_ref) REFERENCES video_video (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE video_video_genre ADD CONSTRAINT FK_2EB08BFBF2F1CD16 FOREIGN KEY (genre_ref) REFERENCES video_genre (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE video_season ADD CONSTRAINT FK_C8B3FB6497FDD6DA FOREIGN KEY (group_ref) REFERENCES video_group (id) ON DELETE SET NULL NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE video_season ADD CONSTRAINT FK_C8B3FB641F274CE3 FOREIGN KEY (directory_ref) REFERENCES file_directory (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE video_season_image ADD CONSTRAINT FK_73FFE24F8E217473 FOREIGN KEY (season_ref) REFERENCES video_season (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE video_season_image ADD CONSTRAINT FK_73FFE24F3B2CB03A FOREIGN KEY (file_ref) REFERENCES file_file (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE tunnel_person ADD CONSTRAINT FK_C56FB71DC44FB2DF FOREIGN KEY (tunnel_ref) REFERENCES system_tunnel (id) ON DELETE SET NULL NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE tunnel_person ADD CONSTRAINT FK_C56FB71D9722F9B8 FOREIGN KEY (person_ref) REFERENCES common_person (id) ON DELETE SET NULL NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE tunnel_person_image ADD CONSTRAINT FK_A68B9E7C9722F9B8 FOREIGN KEY (person_ref) REFERENCES tunnel_person (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE tunnel_person_image ADD CONSTRAINT FK_A68B9E7C3B2CB03A FOREIGN KEY (file_ref) REFERENCES file_file (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE tunnel_group ADD CONSTRAINT FK_A446D1497FDD6DA FOREIGN KEY (group_ref) REFERENCES video_group (id) ON DELETE SET NULL NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE tunnel_group ADD CONSTRAINT FK_A446D14C44FB2DF FOREIGN KEY (tunnel_ref) REFERENCES system_tunnel (id) ON DELETE SET NULL NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE tunnel_group_image ADD CONSTRAINT FK_AF01510E97FDD6DA FOREIGN KEY (group_ref) REFERENCES tunnel_group (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE tunnel_group_image ADD CONSTRAINT FK_AF01510E3B2CB03A FOREIGN KEY (file_ref) REFERENCES file_file (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE tunnel_video ADD CONSTRAINT FK_1B43F3FDC44FB2DF FOREIGN KEY (tunnel_ref) REFERENCES system_tunnel (id) ON DELETE SET NULL NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE tunnel_video ADD CONSTRAINT FK_1B43F3FDEEF6FBA7 FOREIGN KEY (video_ref) REFERENCES video_video (id) ON DELETE SET NULL NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE tunnel_video_image ADD CONSTRAINT FK_704F73CBEEF6FBA7 FOREIGN KEY (video_ref) REFERENCES tunnel_video (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE tunnel_video_image ADD CONSTRAINT FK_704F73CB3B2CB03A FOREIGN KEY (file_ref) REFERENCES file_file (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE tunnel_season ADD CONSTRAINT FK_1573DC28E217473 FOREIGN KEY (season_ref) REFERENCES video_season (id) ON DELETE SET NULL NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE tunnel_season ADD CONSTRAINT FK_1573DC2C44FB2DF FOREIGN KEY (tunnel_ref) REFERENCES system_tunnel (id) ON DELETE SET NULL NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE tunnel_season_image ADD CONSTRAINT FK_1D8C76678E217473 FOREIGN KEY (season_ref) REFERENCES tunnel_season (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE tunnel_season_image ADD CONSTRAINT FK_1D8C76673B2CB03A FOREIGN KEY (file_ref) REFERENCES file_file (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE fos_user_user_group ADD CONSTRAINT FK_B3C77447A76ED395 FOREIGN KEY (user_id) REFERENCES fos_user_user (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE fos_user_user_group ADD CONSTRAINT FK_B3C77447FE54D947 FOREIGN KEY (group_id) REFERENCES fos_user_group (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE acl_object_identities ADD CONSTRAINT FK_9407E54977FA751A FOREIGN KEY (parent_object_identity_id) REFERENCES acl_object_identities (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE acl_object_identity_ancestors ADD CONSTRAINT FK_825DE2993D9AB4A6 FOREIGN KEY (object_identity_id) REFERENCES acl_object_identities (id) ON UPDATE CASCADE ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE acl_object_identity_ancestors ADD CONSTRAINT FK_825DE299C671CEA1 FOREIGN KEY (ancestor_id) REFERENCES acl_object_identities (id) ON UPDATE CASCADE ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE acl_entries ADD CONSTRAINT FK_46C8B806EA000B10 FOREIGN KEY (class_id) REFERENCES acl_classes (id) ON UPDATE CASCADE ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE acl_entries ADD CONSTRAINT FK_46C8B8063D9AB4A6 FOREIGN KEY (object_identity_id) REFERENCES acl_object_identities (id) ON UPDATE CASCADE ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE acl_entries ADD CONSTRAINT FK_46C8B806DF9183C9 FOREIGN KEY (security_identity_id) REFERENCES acl_security_identities (id) ON UPDATE CASCADE ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE');
    }

    public function down(Schema $schema)
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->abortIf($this->connection->getDatabasePlatform()->getName() != 'postgresql', 'Migration can only be executed safely on \'postgresql\'.');
        
        $this->addSql('CREATE SCHEMA public');
        $this->addSql('ALTER TABLE system_job DROP CONSTRAINT FK_36604A234A4533A0');
        $this->addSql('ALTER TABLE system_job DROP CONSTRAINT FK_36604A236D8C5E54');
        $this->addSql('ALTER TABLE system_job DROP CONSTRAINT FK_36604A23E04C0C7F');
        $this->addSql('ALTER TABLE system_setting DROP CONSTRAINT FK_7307C40BF81C3757');
        $this->addSql('ALTER TABLE system_tunnel DROP CONSTRAINT FK_C5F3E081F81C3757');
        $this->addSql('ALTER TABLE tunnel_person DROP CONSTRAINT FK_C56FB71DC44FB2DF');
        $this->addSql('ALTER TABLE tunnel_group DROP CONSTRAINT FK_A446D14C44FB2DF');
        $this->addSql('ALTER TABLE tunnel_video DROP CONSTRAINT FK_1B43F3FDC44FB2DF');
        $this->addSql('ALTER TABLE tunnel_season DROP CONSTRAINT FK_1573DC2C44FB2DF');
        $this->addSql('ALTER TABLE common_person_image DROP CONSTRAINT FK_3FE2E1673B2CB03A');
        $this->addSql('ALTER TABLE video_video_file_meta DROP CONSTRAINT FK_71EF50A43B2CB03A');
        $this->addSql('ALTER TABLE video_staff_image DROP CONSTRAINT FK_9A5A1D393B2CB03A');
        $this->addSql('ALTER TABLE video_video_file DROP CONSTRAINT FK_BAF737A3B2CB03A');
        $this->addSql('ALTER TABLE video_group_image DROP CONSTRAINT FK_B7939E993B2CB03A');
        $this->addSql('ALTER TABLE video_video_image DROP CONSTRAINT FK_68DDBC5C3B2CB03A');
        $this->addSql('ALTER TABLE video_season_image DROP CONSTRAINT FK_73FFE24F3B2CB03A');
        $this->addSql('ALTER TABLE tunnel_person_image DROP CONSTRAINT FK_A68B9E7C3B2CB03A');
        $this->addSql('ALTER TABLE tunnel_group_image DROP CONSTRAINT FK_AF01510E3B2CB03A');
        $this->addSql('ALTER TABLE tunnel_video_image DROP CONSTRAINT FK_704F73CB3B2CB03A');
        $this->addSql('ALTER TABLE tunnel_season_image DROP CONSTRAINT FK_1D8C76673B2CB03A');
        $this->addSql('ALTER TABLE file_file DROP CONSTRAINT FK_5635E7E1F274CE3');
        $this->addSql('ALTER TABLE file_directory DROP CONSTRAINT FK_C877FBACC3A12F71');
        $this->addSql('ALTER TABLE video_group DROP CONSTRAINT FK_E2A24D671F274CE3');
        $this->addSql('ALTER TABLE video_season DROP CONSTRAINT FK_C8B3FB641F274CE3');
        $this->addSql('ALTER TABLE common_person DROP CONSTRAINT FK_4FEA42E32F470832');
        $this->addSql('ALTER TABLE video_file_language DROP CONSTRAINT FK_6EF1D2182F470832');
        $this->addSql('ALTER TABLE video_video DROP CONSTRAINT FK_F3A5D38E2F470832');
        $this->addSql('ALTER TABLE common_person_image DROP CONSTRAINT FK_3FE2E1679722F9B8');
        $this->addSql('ALTER TABLE video_staff DROP CONSTRAINT FK_CD0CFA309722F9B8');
        $this->addSql('ALTER TABLE tunnel_person DROP CONSTRAINT FK_C56FB71D9722F9B8');
        $this->addSql('ALTER TABLE video_staff_image DROP CONSTRAINT FK_9A5A1D399A63A56A');
        $this->addSql('ALTER TABLE video_video DROP CONSTRAINT FK_F3A5D38E1858326A');
        $this->addSql('ALTER TABLE video_file_language DROP CONSTRAINT FK_6EF1D21893AE8286');
        $this->addSql('ALTER TABLE video_video_file DROP CONSTRAINT FK_BAF737AE860DF97');
        $this->addSql('ALTER TABLE video_video_file DROP CONSTRAINT FK_BAF737A248BBD90');
        $this->addSql('ALTER TABLE video_staff DROP CONSTRAINT FK_CD0CFA305FC5E53D');
        $this->addSql('ALTER TABLE video_video DROP CONSTRAINT FK_F3A5D38EDB6035A');
        $this->addSql('ALTER TABLE video_video_file DROP CONSTRAINT FK_BAF737A8A086E0A');
        $this->addSql('ALTER TABLE video_group_image DROP CONSTRAINT FK_B7939E9997FDD6DA');
        $this->addSql('ALTER TABLE video_group_genre DROP CONSTRAINT FK_F1FEA93E97FDD6DA');
        $this->addSql('ALTER TABLE video_video DROP CONSTRAINT FK_F3A5D38E97FDD6DA');
        $this->addSql('ALTER TABLE video_season DROP CONSTRAINT FK_C8B3FB6497FDD6DA');
        $this->addSql('ALTER TABLE tunnel_group DROP CONSTRAINT FK_A446D1497FDD6DA');
        $this->addSql('ALTER TABLE video_staff DROP CONSTRAINT FK_CD0CFA30EEF6FBA7');
        $this->addSql('ALTER TABLE video_video_file DROP CONSTRAINT FK_BAF737AEEF6FBA7');
        $this->addSql('ALTER TABLE video_character DROP CONSTRAINT FK_5105CDA1EEF6FBA7');
        $this->addSql('ALTER TABLE video_video_image DROP CONSTRAINT FK_68DDBC5CEEF6FBA7');
        $this->addSql('ALTER TABLE video_video_genre DROP CONSTRAINT FK_2EB08BFBEEF6FBA7');
        $this->addSql('ALTER TABLE tunnel_video DROP CONSTRAINT FK_1B43F3FDEEF6FBA7');
        $this->addSql('ALTER TABLE video_group_genre DROP CONSTRAINT FK_F1FEA93EF2F1CD16');
        $this->addSql('ALTER TABLE video_video_genre DROP CONSTRAINT FK_2EB08BFBF2F1CD16');
        $this->addSql('ALTER TABLE video_video DROP CONSTRAINT FK_F3A5D38E8E217473');
        $this->addSql('ALTER TABLE video_season_image DROP CONSTRAINT FK_73FFE24F8E217473');
        $this->addSql('ALTER TABLE tunnel_season DROP CONSTRAINT FK_1573DC28E217473');
        $this->addSql('ALTER TABLE tunnel_person_image DROP CONSTRAINT FK_A68B9E7C9722F9B8');
        $this->addSql('ALTER TABLE tunnel_group_image DROP CONSTRAINT FK_AF01510E97FDD6DA');
        $this->addSql('ALTER TABLE tunnel_video_image DROP CONSTRAINT FK_704F73CBEEF6FBA7');
        $this->addSql('ALTER TABLE tunnel_season_image DROP CONSTRAINT FK_1D8C76678E217473');
        $this->addSql('ALTER TABLE fos_user_user_group DROP CONSTRAINT FK_B3C77447A76ED395');
        $this->addSql('ALTER TABLE fos_user_user_group DROP CONSTRAINT FK_B3C77447FE54D947');
        $this->addSql('ALTER TABLE acl_entries DROP CONSTRAINT FK_46C8B806EA000B10');
        $this->addSql('ALTER TABLE acl_entries DROP CONSTRAINT FK_46C8B806DF9183C9');
        $this->addSql('ALTER TABLE acl_object_identities DROP CONSTRAINT FK_9407E54977FA751A');
        $this->addSql('ALTER TABLE acl_object_identity_ancestors DROP CONSTRAINT FK_825DE2993D9AB4A6');
        $this->addSql('ALTER TABLE acl_object_identity_ancestors DROP CONSTRAINT FK_825DE299C671CEA1');
        $this->addSql('ALTER TABLE acl_entries DROP CONSTRAINT FK_46C8B8063D9AB4A6');
        $this->addSql('DROP SEQUENCE fos_user_user_id_seq CASCADE');
        $this->addSql('DROP SEQUENCE fos_user_group_id_seq CASCADE');
        $this->addSql('DROP TABLE system_job');
        $this->addSql('DROP TABLE system_module');
        $this->addSql('DROP TABLE system_setting');
        $this->addSql('DROP TABLE system_tunnel');
        $this->addSql('DROP TABLE file_file');
        $this->addSql('DROP TABLE file_directory');
        $this->addSql('DROP TABLE file_extension');
        $this->addSql('DROP TABLE common_country');
        $this->addSql('DROP TABLE common_person');
        $this->addSql('DROP TABLE common_person_image');
        $this->addSql('DROP TABLE video_video_file_meta');
        $this->addSql('DROP TABLE video_staff');
        $this->addSql('DROP TABLE video_staff_image');
        $this->addSql('DROP TABLE video_review');
        $this->addSql('DROP TABLE video_video_file');
        $this->addSql('DROP TABLE video_file_language');
        $this->addSql('DROP TABLE video_stat');
        $this->addSql('DROP TABLE video_group_type');
        $this->addSql('DROP TABLE video_picture');
        $this->addSql('DROP TABLE video_staff_role');
        $this->addSql('DROP TABLE video_character');
        $this->addSql('DROP TABLE video_rating');
        $this->addSql('DROP TABLE video_type');
        $this->addSql('DROP TABLE video_quality');
        $this->addSql('DROP TABLE video_group');
        $this->addSql('DROP TABLE video_group_image');
        $this->addSql('DROP TABLE video_group_genre');
        $this->addSql('DROP TABLE video_video');
        $this->addSql('DROP TABLE video_video_image');
        $this->addSql('DROP TABLE video_video_genre');
        $this->addSql('DROP TABLE video_genre');
        $this->addSql('DROP TABLE video_season');
        $this->addSql('DROP TABLE video_season_image');
        $this->addSql('DROP TABLE tunnel_person');
        $this->addSql('DROP TABLE tunnel_person_image');
        $this->addSql('DROP TABLE tunnel_group');
        $this->addSql('DROP TABLE tunnel_group_image');
        $this->addSql('DROP TABLE tunnel_video');
        $this->addSql('DROP TABLE tunnel_video_image');
        $this->addSql('DROP TABLE tunnel_season');
        $this->addSql('DROP TABLE tunnel_season_image');
        $this->addSql('DROP TABLE fos_user_user');
        $this->addSql('DROP TABLE fos_user_user_group');
        $this->addSql('DROP TABLE fos_user_group');
        $this->addSql('DROP TABLE acl_classes');
        $this->addSql('DROP TABLE acl_security_identities');
        $this->addSql('DROP TABLE acl_object_identities');
        $this->addSql('DROP TABLE acl_object_identity_ancestors');
        $this->addSql('DROP TABLE acl_entries');
    }
}
