services:
    mediamine.elastica.hydrator.video:
        class: MediaMine\CoreBundle\Elastica\Hydrator\ElasticaToVideoTransformer
        arguments: [@doctrine, "\MediaMine\CoreBundle\Entity\Video\Video", {hydrate:false}]
        calls:
            - [ setEntityManagerRegistry, [ @doctrine ] ]
            - [ setPropertyAccessor, [ @fos_elastica.property_accessor ] ]
        tags:
            - { name: fos_elastica.elastica_to_model_transformer, type: Video, index: search}
    mediamine.elastica.hydrator.group:
        class: MediaMine\CoreBundle\Elastica\Hydrator\ElasticaToGroupTransformer
        arguments: [@doctrine, "\MediaMine\CoreBundle\Entity\Video\Group", {hydrate:false}]
        calls:
            - [ setEntityManagerRegistry, [ @doctrine ] ]
            - [ setPropertyAccessor, [ @fos_elastica.property_accessor ] ]
        tags:
            - { name: fos_elastica.elastica_to_model_transformer, type: Group, index: search}
    mediamine.elastica.hydrator.person:
        class: MediaMine\CoreBundle\Elastica\Hydrator\ElasticaToPersonTransformer
        arguments: [@doctrine, "\MediaMine\CoreBundle\Entity\Common\Person", {hydrate:false}]
        calls:
            - [ setEntityManagerRegistry, [ @doctrine ] ]
            - [ setPropertyAccessor, [ @fos_elastica.property_accessor ] ]
        tags:
            - { name: fos_elastica.elastica_to_model_transformer, type: Person, index: search}